#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include "uart0.h"
#include "wait.h"
#include "tm4c123gh6pm.h"

void enableISR()
{
    NVIC_SYS_HND_CTRL_R |= NVIC_SYS_HND_CTRL_BUS;   // bus fault
    NVIC_SYS_HND_CTRL_R |= NVIC_SYS_HND_CTRL_USAGE; // usage fault
    NVIC_SYS_HND_CTRL_R |= NVIC_SYS_HND_CTRL_MEM;   // MPU fault
}

void enableMPU()
{
    NVIC_MPU_CTRL_R |= NVIC_MPU_CTRL_ENABLE;
}

void MPUOn()
{
    //background rule
    NVIC_MPU_NUMBER_R = 0;
    NVIC_MPU_BASE_R |= 0x00000000 | NVIC_MPU_BASE_VALID;
    NVIC_MPU_ATTR_R |= NVIC_MPU_ATTR_XN | 0x03000000 | NVIC_MPU_ATTR_SHAREABLE | NVIC_MPU_ATTR_CACHEABLE | NVIC_MPU_ATTR_BUFFRABLE | NVIC_MPU_ATTR_SIZE_M | NVIC_MPU_ATTR_ENABLE;

    //full access MPU for flash
    NVIC_MPU_NUMBER_R = 1;
    NVIC_MPU_BASE_R |= 0x00000000 | NVIC_MPU_BASE_VALID;
    NVIC_MPU_ATTR_R |= 0x03000000 | NVIC_MPU_ATTR_CACHEABLE | 0x00000022 | NVIC_MPU_ATTR_ENABLE; // 256KB

    //32KiB SRAM (4 regions x 8 subregions). Disable all subregions
    NVIC_MPU_NUMBER_R = 2;
    NVIC_MPU_BASE_R |= 0x20000000 | NVIC_MPU_BASE_VALID;
    NVIC_MPU_ATTR_R |= 0x01000000 | NVIC_MPU_ATTR_SHAREABLE | NVIC_MPU_ATTR_CACHEABLE | 0x00000014 | NVIC_MPU_ATTR_ENABLE; //8KB

    NVIC_MPU_NUMBER_R = 3;
    NVIC_MPU_BASE_R |= 0x20002000 | NVIC_MPU_BASE_VALID;
    NVIC_MPU_ATTR_R |= 0x01000000 | NVIC_MPU_ATTR_SHAREABLE | NVIC_MPU_ATTR_CACHEABLE | 0x00000014 | NVIC_MPU_ATTR_ENABLE;

    NVIC_MPU_NUMBER_R = 4;
    NVIC_MPU_BASE_R |= 0x20004000 | NVIC_MPU_BASE_VALID;
    NVIC_MPU_ATTR_R |= 0x01000000 | NVIC_MPU_ATTR_SHAREABLE | NVIC_MPU_ATTR_CACHEABLE | 0x00000014 | NVIC_MPU_ATTR_ENABLE;

    NVIC_MPU_NUMBER_R = 5;
    NVIC_MPU_BASE_R |= 0x20006000 | NVIC_MPU_BASE_VALID;
    NVIC_MPU_ATTR_R |= 0x01000000 | NVIC_MPU_ATTR_SHAREABLE | NVIC_MPU_ATTR_CACHEABLE | 0x00000014 | NVIC_MPU_ATTR_ENABLE;

}

void setSRDBit(uint32_t srd)
{
    NVIC_MPU_NUMBER_R = 2;
    //NVIC_MPU_ATTR_R &= ~(0x0000FF00);
    NVIC_MPU_ATTR_R |= ((srd >> 0) & 0xFF) << 8 | NVIC_MPU_ATTR_ENABLE;

    NVIC_MPU_NUMBER_R = 3;
    //NVIC_MPU_ATTR_R &= ~(0x0000FF00);
    NVIC_MPU_ATTR_R |= ((srd >> 8) & 0xFF) << 8 | NVIC_MPU_ATTR_ENABLE;

    NVIC_MPU_NUMBER_R = 4;
    //NVIC_MPU_ATTR_R &= ~(0x0000FF00);
    NVIC_MPU_ATTR_R |= ((srd >> 16) & 0xFF) << 8 | NVIC_MPU_ATTR_ENABLE;

    NVIC_MPU_NUMBER_R = 5;
    //NVIC_MPU_ATTR_R &= ~(0x0000FF00);
    NVIC_MPU_ATTR_R |= ((srd >> 24) & 0xFF) << 8 | NVIC_MPU_ATTR_ENABLE;
}





